server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/nomorework
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

flyway:
  locations: classpath:db/migration
  baseline-on-migrate: true

